# Generated by Django 4.2.16 on 2025-01-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True},
        ),
    ]
